/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
import javax.swing.table.DefaultTableModel;
import javax.swing.*;
import java.util.ArrayList;
import model.*;
import java.util.Queue;
import controller.*;
/**
 *
 * @author Admin
 */
public class UserDashboard extends javax.swing.JFrame {
    
    private MovieController controller = new MovieController();
    private WatchlistController watchlistController = new WatchlistController();

    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(UserDashboard.class.getName());
    
    public void loadMovieTable() {
    DefaultTableModel model = (DefaultTableModel) movieTable.getModel();
    model.setRowCount(0); // clear table

    for (Movie m : controller.readMovie()) {
        model.addRow(new Object[]{
            m.getID(),
            m.getName(),
            m.getGenre(),
            m.getYear(),
            m.getRating()
        });
    }
  }
    
    public void loadRecentMovies() {

    DefaultTableModel model =
        (DefaultTableModel) recentTable.getModel();

    model.setRowCount(0);

    Queue<Movie> recentMovies = controller.getRecentMovies();

    // FIFO: iterate from front to rear
    for (Movie m : recentMovies) {
        model.addRow(new Object[]{
            m.getName()
        });
    }
  }



  


    /**
     * Creates new form UserDashboard
     */
    public UserDashboard() {
        initComponents();
        loadMovieTable();
        loadRecentMovies();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        sortBox = new javax.swing.JComboBox<>();
        sortBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        movieTable = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        watchlistbtn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        recentTable = new javax.swing.JTable();
        jButton5 = new javax.swing.JButton();
        searchByBox = new javax.swing.JComboBox<>();
        btnSearch = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        viewwlbtn = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1280, 720));
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setPreferredSize(new java.awt.Dimension(1280, 720));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 24)); // NOI18N
        jLabel2.setText("MOVIE VAULT - USER Dashboard");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, -1, -1));

        jPanel3.setBackground(new java.awt.Color(204, 255, 255));

        jLabel3.setText("Search:");

        txtSearch.addActionListener(this::txtSearchActionPerformed);

        jLabel4.setText("Sort By: ");

        sortBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Movie ID", "Movie Name", "Release Year", "Rating" }));
        sortBox.addActionListener(this::sortBoxActionPerformed);

        sortBtn.setText("SORT");
        sortBtn.addActionListener(this::sortBtnActionPerformed);

        movieTable.setBackground(new java.awt.Color(0, 0, 0));
        movieTable.setForeground(new java.awt.Color(255, 255, 255));
        movieTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Movie ID", "Movie Name", "Movie Genre", "Release Year", "Rating"
            }
        ));
        jScrollPane1.setViewportView(movieTable);

        jLabel6.setText("Movie ID:");

        watchlistbtn.setText("Add to WatchList");
        watchlistbtn.addActionListener(this::watchlistbtnActionPerformed);

        recentTable.setBackground(new java.awt.Color(0, 0, 0));
        recentTable.setForeground(new java.awt.Color(255, 255, 255));
        recentTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Recently Added Movies to the vault"
            }
        ));
        jScrollPane2.setViewportView(recentTable);

        jButton5.setText("Refresh");
        jButton5.addActionListener(this::jButton5ActionPerformed);

        searchByBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Movie Name", "Release Year" }));
        searchByBox.addActionListener(this::searchByBoxActionPerformed);

        btnSearch.setBackground(new java.awt.Color(204, 204, 255));
        btnSearch.setText("SEARCH");
        btnSearch.addActionListener(this::btnSearchActionPerformed);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(watchlistbtn)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(searchByBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(btnSearch)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sortBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(sortBtn)
                        .addGap(174, 174, 174))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton5)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 461, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 51, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(sortBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sortBtn)
                    .addComponent(searchByBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch))
                .addGap(27, 27, 27)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 374, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5)
                .addGap(15, 15, 15)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(watchlistbtn))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 980, 560));

        jButton1.setBackground(new java.awt.Color(204, 255, 255));
        jButton1.setText("LOGOUT");
        jButton1.addActionListener(this::jButton1ActionPerformed);
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 40, 100, 40));

        viewwlbtn.setBackground(new java.awt.Color(204, 255, 255));
        viewwlbtn.setText("VIEW WATCHLIST");
        viewwlbtn.addActionListener(this::viewwlbtnActionPerformed);
        jPanel1.add(viewwlbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 40, 130, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/photo-1635776062043-223faf322554 (1).jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setMaximumSize(new java.awt.Dimension(1280, 720));
        jLabel1.setMinimumSize(new java.awt.Dimension(1280, 720));
        jLabel1.setPreferredSize(new java.awt.Dimension(1280, 720));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 730));

        jLabel5.setText("jLabel5");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 680, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    
    LoginRegister login = new LoginRegister();
    login.setVisible(true);
    this.dispose();

    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchActionPerformed

    private void sortBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sortBtnActionPerformed

    String sortType = sortBox.getSelectedItem().toString();

    ArrayList<Movie> list =
        new ArrayList<>(controller.readMovie());

    if (sortType.equals("Movie ID")) {
    SelectionSort.sortById(list);
    }
    else if (sortType.equals("Movie Name")) {
    InsertionSort.sortByName(list);
    }
     else if (sortType.equals("Release Year")) {
    MergeSort.sortByYear(list);
    }
    else if (sortType.equals("Rating")) {
    SelectionSort.sortByRating(list);
    }


    DefaultTableModel model =
        (DefaultTableModel) movieTable.getModel();

    model.setRowCount(0);

    for (int i = 0; i < list.size(); i++) {
        Movie m = list.get(i);
        model.addRow(new Object[]{
            m.getID(),
            m.getName(),
            m.getGenre(),
            m.getYear(),
            m.getRating()
        });
    }


    }//GEN-LAST:event_sortBtnActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        loadMovieTable();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void sortBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sortBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sortBoxActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
    String keyword = txtSearch.getText();
    String criteria = searchByBox.getSelectedItem().toString();

    if (keyword.equals("")) {
        JOptionPane.showMessageDialog(this, "Please enter a search value");
        return;
    }

    DefaultTableModel model =
        (DefaultTableModel) movieTable.getModel();
    model.setRowCount(0);

    // Linear Search for Movie Name
    if (criteria.equals("Movie Name")) {

        ArrayList<Movie> results =
            controller.searchMovie(keyword, criteria);

        for (int i = 0; i < results.size(); i++) {
            Movie m = results.get(i);
            model.addRow(new Object[]{
                m.getID(),
                m.getName(),
                m.getGenre(),
                m.getYear(),
                m.getRating()
            });
        }

        if (results.size() == 0) {
            JOptionPane.showMessageDialog(this, "No matching movies found");
        }
    }

    // Binary Search for Release Year
    else if (criteria.equals("Release Year")) {

        if (!keyword.matches("\\d+")) {
            JOptionPane.showMessageDialog(this, "Please enter a valid year");
            return;
        }

        int year = Integer.parseInt(keyword);
        Movie result = controller.binarySearchByYear(year);

        if (result != null) {
            model.addRow(new Object[]{
                result.getID(),
                result.getName(),
                result.getGenre(),
                result.getYear(),
                result.getRating()
            });
        } else {
            JOptionPane.showMessageDialog(this, "No movie found for this year");
        }
    }


    }//GEN-LAST:event_btnSearchActionPerformed

    private void searchByBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchByBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchByBoxActionPerformed

    private void watchlistbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_watchlistbtnActionPerformed
        String idText = jTextField2.getText();

    if (idText.equals("")) {
        JOptionPane.showMessageDialog(this, "Enter Movie ID");
        return;
    }

    if (!idText.matches("\\d+")) {
        JOptionPane.showMessageDialog(this, "Movie ID must be a number");
        return;
    }

    int id = Integer.parseInt(idText);

    Movie movie = controller.getMovieById(id);

    if (movie == null) {
        JOptionPane.showMessageDialog(this, "Movie not found");
        return;
    }

    boolean added = watchlistController.addToWatchlist(movie);

    if (added) {
        JOptionPane.showMessageDialog(this, "Movie added to watchlist");
    } else {
        JOptionPane.showMessageDialog(this, "Movie already in watchlist");
    }
    }//GEN-LAST:event_watchlistbtnActionPerformed

    private void viewwlbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewwlbtnActionPerformed
         UserHome home = new UserHome();
         home.setVisible(true);
         this.dispose(); // close dashboard
    }//GEN-LAST:event_viewwlbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new UserDashboard().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTable movieTable;
    private javax.swing.JTable recentTable;
    private javax.swing.JComboBox<String> searchByBox;
    private javax.swing.JComboBox<String> sortBox;
    private javax.swing.JButton sortBtn;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JToggleButton viewwlbtn;
    private javax.swing.JButton watchlistbtn;
    // End of variables declaration//GEN-END:variables
}
